package policy

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/Super-Protocol/confidential-router/apps/gatekeeper/pkg/trust"
)

// TrustPackage is the generated, read-only data module every policy reads.
const TrustPackage = "gatekeeper.trust"

// trustModuleFilename is what compile errors and traces refer to. It is not a
// real path — the module never exists on disk.
const trustModuleFilename = "gatekeeper.trust.rego"

// GenerateTrustModule renders the trust store as a Rego module (ADR-003 §4).
//
// Generating a module rather than pushing a data document keeps everything the
// policies see in one compiled unit: `opa eval` over the same files reproduces
// a gatekeeper decision exactly. The output is deterministic — the snapshot is
// sorted — so it is diffable and can be asserted on in tests.
func GenerateTrustModule(snap trust.Snapshot) string {
	var b strings.Builder
	b.WriteString("# Code generated by the gatekeeper from its configuration. DO NOT EDIT.\n")
	b.WriteString("package " + TrustPackage + "\n\n")

	b.WriteString("roots := {")
	if len(snap.Roots) == 0 {
		b.WriteString("}\n\n")
	} else {
		b.WriteString("\n")
		for _, r := range snap.Roots {
			fmt.Fprintf(&b, "\t%s: {\"fingerprint\": %s},\n", quote(r.Name), quote(r.Fingerprint))
		}
		b.WriteString("}\n\n")
	}

	b.WriteString("endpoints := {")
	if len(snap.Endpoints) == 0 {
		b.WriteString("}\n")
		return b.String()
	}
	b.WriteString("\n")
	for _, ep := range snap.Endpoints {
		fmt.Fprintf(&b, "\t%s: {\n", quote(ep.Name))
		fmt.Fprintf(&b, "\t\t\"hostname\": %s,\n", quote(ep.Hostname))
		fmt.Fprintf(&b, "\t\t\"fail_mode\": %s,\n", quote(ep.FailMode))
		fmt.Fprintf(&b, "\t\t\"evidence_digests\": %s,\n", set(ep.Digests))
		fmt.Fprintf(&b, "\t\t\"evidence_digests_hex\": %s,\n", set(ep.DigestsHex))
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n")
	return b.String()
}

// set renders a Rego set literal. `{}` is an empty *object* in Rego, so the
// empty set has to be spelled `set()` — otherwise `some x in …` over an
// endpoint with no pins would silently iterate an object.
func set(values []string) string {
	if len(values) == 0 {
		return "set()"
	}
	quoted := make([]string, 0, len(values))
	for _, v := range values {
		quoted = append(quoted, quote(v))
	}
	return "{" + strings.Join(quoted, ", ") + "}"
}

// quote renders a Rego string literal. Rego strings are JSON strings, so
// encoding/json is the right escaper: strconv.Quote would emit Go-only escapes
// such as `\x01` or `\v`, and one of those anywhere in a name would make the
// whole generated module fail to parse.
func quote(s string) string {
	encoded, err := json.Marshal(s)
	if err != nil {
		// json.Marshal of a string only fails on invalid UTF-8, which Marshal
		// itself replaces rather than rejecting.
		panic(fmt.Sprintf("policy: cannot render %q as a Rego string: %v", s, err))
	}
	return string(encoded)
}
