package policy_test

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/Super-Protocol/confidential-router/apps/gatekeeper/pkg/config"
	"github.com/Super-Protocol/confidential-router/apps/gatekeeper/pkg/policy"
	"github.com/Super-Protocol/confidential-router/apps/gatekeeper/pkg/trust"
)

func TestGenerateTrustModuleContent(t *testing.T) {
	snap := trust.Snapshot{
		Roots: []trust.RootSnapshot{
			{Name: "swarm-cloud-prod", Fingerprint: "sha256/CN9TvdttScO-k83aqy-07JEBs_SkKPWJjITtr6_ssAw"},
		},
		Endpoints: []trust.EndpointSnapshot{{
			Name:       "llama-33-70b",
			Hostname:   "llama-33-70b.tee.swarm.cloud",
			FailMode:   "closed",
			Digests:    []string{"sha256/aaa", "sha256/bbb"},
			DigestsHex: []string{"0a", "0b"},
		}},
	}

	const want = `# Code generated by the gatekeeper from its configuration. DO NOT EDIT.
package gatekeeper.trust

roots := {
	"swarm-cloud-prod": {"fingerprint": "sha256/CN9TvdttScO-k83aqy-07JEBs_SkKPWJjITtr6_ssAw"},
}

endpoints := {
	"llama-33-70b": {
		"hostname": "llama-33-70b.tee.swarm.cloud",
		"fail_mode": "closed",
		"evidence_digests": {"sha256/aaa", "sha256/bbb"},
		"evidence_digests_hex": {"0a", "0b"},
	},
}
`
	if got := policy.GenerateTrustModule(snap); got != want {
		t.Errorf("generated module differs\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

func TestGenerateTrustModuleUsesSetForEmptyCollections(t *testing.T) {
	// `{}` is an empty *object* in Rego: emitting it would make `some x in …`
	// iterate the wrong type instead of finding nothing.
	got := policy.GenerateTrustModule(trust.Snapshot{
		Endpoints: []trust.EndpointSnapshot{{Name: "bare", Hostname: "bare.example", FailMode: "closed"}},
	})
	if !strings.Contains(got, `"evidence_digests": set(),`) {
		t.Errorf("empty pin list is not rendered as set():\n%s", got)
	}
	if !strings.Contains(got, "roots := {}") {
		t.Errorf("empty roots map is not rendered:\n%s", got)
	}
}

func TestEngineExposesTheGeneratedTrustModule(t *testing.T) {
	engine := newEngine(t)
	module := engine.TrustModule()

	if !strings.Contains(module, "package "+policy.TrustPackage) {
		t.Errorf("trust module has the wrong package:\n%s", module)
	}
	if !strings.Contains(module, pinnedDigest.String()) {
		t.Errorf("trust module does not carry the configured pin:\n%s", module)
	}
	if !strings.Contains(module, pinnedDigest.Hex()) {
		t.Errorf("trust module does not carry the hex form of the pin:\n%s", module)
	}
}

func TestLoadModulesReadsPolicyFilesRelativeToTheConfig(t *testing.T) {
	dir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(dir, "policies"), 0o750); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "policies", "images.rego"), []byte(registryPolicy), 0o600); err != nil {
		t.Fatal(err)
	}
	cfg := &config.Config{
		Path:     filepath.Join(dir, "config.yaml"),
		Policies: []config.Policy{{Name: "images", File: "./policies/images.rego"}},
	}

	modules, err := policy.LoadModules(cfg)
	if err != nil {
		t.Fatalf("LoadModules: %v", err)
	}
	if len(modules) != 1 || modules[0].Name != "images" || !strings.Contains(modules[0].Source, "package user.images") {
		t.Fatalf("modules = %+v, want the images policy", modules)
	}

	engine, err := policy.New(context.Background(), policy.Options{Store: newStore(t), Modules: modules})
	if err != nil {
		t.Fatalf("policy.New with a loaded module: %v", err)
	}
	if !engine.Evaluate(context.Background(), inputFor(t, "llama", pinnedDigest)).Allow {
		t.Error("the loaded policy denied a bundle it should allow")
	}
}

func TestLoadModulesReportsAMissingFile(t *testing.T) {
	cfg := &config.Config{
		Path:     filepath.Join(t.TempDir(), "config.yaml"),
		Policies: []config.Policy{{Name: "images", File: "./missing.rego"}},
	}
	if _, err := policy.LoadModules(cfg); err == nil || !strings.Contains(err.Error(), `policy "images"`) {
		t.Fatalf("err = %v, want the policy name in the error", err)
	}
}

func TestGenerateTrustModuleEscapesAsRegoNotGo(t *testing.T) {
	// Rego strings are JSON strings. A Go-style escape such as \x01 would make
	// the whole generated module fail to parse, taking the engine — and every
	// endpoint with it — down at load.
	got := policy.GenerateTrustModule(trust.Snapshot{
		Endpoints: []trust.EndpointSnapshot{{
			Name:     "odd",
			Hostname: "host\x01\vname",
			FailMode: "closed",
		}},
	})
	for _, goOnly := range []string{`\x01`, `\v`} {
		if strings.Contains(got, goOnly) {
			t.Errorf("the module carries the Go-only escape %s:\n%s", goOnly, got)
		}
	}
	if !strings.Contains(got, `\u0001`) {
		t.Errorf("the control character was not escaped the JSON way:\n%s", got)
	}
}
